import '../styles/globals.css'
import { Inter, Lexend } from 'next/font/google'
import Header from '../components/header';
import Footer from '../components/footer';

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
})
const lexend = Lexend({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-lexend',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lexend.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
